version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    # volumes:
      # - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:16
    container_name: node
    volumes:
      - ./node:/usr/src/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"

  playwright:
    image: mcr.microsoft.com/playwright:v1.45.1-jammy
    depends_on:
      - wordpress
      - node
    working_dir: /app
    volumes:
      - .:/app
    # entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
